### ISSUE TITLE
Uploading files as part of form submission

### ISSUE THREAD

**Issue by kalmanh** [brucejo75/meteor-file-jsSample-app#1]
First of all, this repo is a great sample! I need to do something a little different (although probably more common). I need to be able to upload file as part of another form, perhaps using autoform package.

So, for example, imagine there is a user form with say first name and last name. As part of that user form, I would like to also be able to upload a profile picture. Both for new user and existing user.

Is it possible to modify your current example to show this scenario? If not - can you describe how this can be achieved?

I am assuming that my UserCollection will have a reference to an _id of FileCollection (or array of FileCollection _ids if there are many)....

**Comment by brucejo75** [comment]
Hi Kalman,

Correct me if I am wrong, are you asking how can you create a form that uploads a picture for a user in your system using [meteor-file-collection](https://github.com/vsivsi/meteor-file-collection)?

What attracted me to [meteor-file-collection](https://github.com/vsivsi/meteor-file-collection) was the capability to support drag and drop along with file upload.  So let's figure out how to incorporate it.

For your scenario, I can imagine a workflow like this:
1. You have a form that has a picture area next to the form.
2. If the picture is uninitialized you show some sort of shadow picture.
3. The user can either upload or drag and drop an image onto the picture area.
4. When the user does that it populates a file in your server files collection (e.g. fs.files).
5. When the user submits the form, you can associate the image file with the user.  e.g. on the user add a field that has the file name?  on the file add the userId to the metadata.  Then you can find this file by selecting `{metadata.user: userId, filename: "userfilename.jpg"}`.  An alternative is to simply name the file `'userId'.jpg`.  You just need a unique selector for each image in your collection.
6. If the user cancels you can delete the file from your collection.

Once the file is loaded in your collection you can simply use one of the [meteor-file-collection](https://github.com/vsivsi/meteor-file-collection) apis, (e.g. [findOne](https://github.com/vsivsi/meteor-file-collection#fcfindoneselector-options)) to find it and use it.

**Comment by kalmanh** [comment]
I am with you through step 4. I would love to see an example of 5 (and 6) provided that I don't know the file name(s) in advance.

**Comment by brucejo75** [comment]
At step 4 you will have the file name.  It is captured by meteor-file-collection.  Run the sample in debug and set a breakpoint [here](https://github.com/brucejo75/meteor-file-jsSample-app/blob/master/server/sample.js#L34).  Take a look at the file object.  It has the file name.  Plus, note that the file can be extended (e.g. `file.metadata._auth = {'owner': userId};`).  So you could do things like change the file name you store and / or add the userId into the metadata like the example does.  I think you gain all the flexibility you need at that point.

Then take a look at the collection side and examine the data in your mongo DB.  Get familiar with `meteor mongo`  &/or a tool like [robomongo](https://robomongo.org/).

**Comment by kalmanh** [comment]
@brucejo75 I understand that part. Here is the part I am missing, the file insert happens [here](https://github.com/brucejo75/meteor-file-jsSample-app/blob/master/client/sample.js#L5) inside 'fileAdded' listener, but in this listener I have no idea what my userId is (not the user who is logged in, but a user for whom I am creating a profile). User was probably a bad example. Let's say a book and book cover or something like that. When a 'book cover file' is added - I have no idea what book _id is (especially if the book is just now being "created" and doesn't even have an _id yet since it hasn't been submitted yet). I guess I can use an [onSubmit hook](https://github.com/aldeed/meteor-autoform#callbackshooks) or something and insert a 'metadata.book_id' into Uploads once I know what the book _id is? Feels kinda lame... Also, for the f[iles helper](https://github.com/brucejo75/meteor-file-jsSample-app/blob/master/client/colltest.js#L78) I wouldn't want ALL book covers in this case, but only this particular one. Which means that I need to fetch 1. book cover without a metadata.book_id OR 2. book cover with metadata.book_id that is equal to the book _id I am currently looking at... which means that I would need to pass that information into the coltest template somehow...

I can probably [stumble myself through this one](https://www.youtube.com/watch?v=pMd_aGc6x1k), but would be nice to see an example of someone with more experience with Meteor and someone who understands file-collection

**Comment by brucejo75** [comment]
Oh I see, you want to upload data for user A (or some other independent object) while logged in as user B.

I am in the process of implementing this for my own app right now.  Here is my plan:
1. Move the `Uploads.resumable` events from `Meteor.startup` to the templates where I need them.  e.g. declare them in the `onCreated` event.
2. The templates where I declare/use them will be within another context (e.g. parent template) that define the target of the files.  For example, who the intended owner is.
3. Within the `onCreated` template event I can reference the needed variables within the `Uploads.resumable` event declarations using closure.  That is, I can declare and set the needed variables in the outer `onCreated` and reference them in the `Uploads.resumable` event declarations.

Understands file-collection?  Ha! So far, my only experience with file-collection is having ported the demo over to JS.  You might want to check in with @vsivsi the author of file-collection  Maybe there is a better way?

**Comment by kalmanh** [comment]
Interesting approach. I see 2 issues with this approach:
1. If you create a listener inside `onCreated` of the template, you also need a way to destroy it, no?
2. You might not always have the necessary vars for the parent id. For example, if this is a new book resource you are creating, it hasn't been saved yet, so no `_id` exists (that you can pass to `metada.book_id` for example).

The approach I am exploring is leaving `fileAdded` where it is right now, but adding the `_id` of the new file to  `Session` inside the `fileAdded` event handler. This way once I submit the book, I can also add the files (whose `_id`s are stored in the `Session`).

As far as the `files` helper, I can query for files with `metadata.book_id` OR newly created files (whose `_id`s I would have in the `Session`)

**Comment by brucejo75** [comment]
I just got my solution working.
1. It is an event handler.  I do not think I need to destroy it?  If I am on other templates I will not be able to reach the UI for upload.  So simply reassigning it on each `onCreated` should work.  When the template closes down I am assuming that the declaration instances will be freed?  I am not up to speed on memory management for this.  I had been assuming that the garbage collector could clear it up.  but maybe you are right re: the event handler hanging on to the function declaration so the garbage collector cannot reclaim.  Maybe I can do something in the `onDestroyed` event.
2. I am using template variables.  So I set them in the helper and refer to the values in the function call and that works fine.

The advantage to my approach is re-usability of the template.  I have at least 2 places I need to upload files, now I can reuse the template for both.  If I used session variables I would need to create a way to manage it for each instance.

Your solution re: saving the file id in the book collection sounds good.  As soon as I have my file I have already created my parent object, so I am able to set that stuff directly.

Either way, you have a couple of options.  Let me know if you get it sorted.

**Comment by brucejo75** [comment]
BTW: I checked on memory leaking for the event handlers.  Essentially, you do not need to destroy the pointers to handlers.  When I reassign the handler it will free up the memory previously pointed to.

If I wanted to be exacting about it, I could set the handler to null in the `onDestroyed` event.

Some good articles:
[four-types-of-leaks-in-your-javascript-code-and-how-to-get-rid-of-them](https://auth0.com/blog/2016/01/26/four-types-of-leaks-in-your-javascript-code-and-how-to-get-rid-of-them/)
[node-js-performance-garbage-collection](https://strongloop.com/strongblog/node-js-performance-garbage-collection/)

I will do some measurements at some point down the road...

**Comment by kalmanh** [comment]
I got mine working with a `Session`. I agree that yours is probably a better solution in that it is reusable.

Would love to see it if you care to make a sample repo out of it. Will try to put mine up there somewhere as well if anyone stumbles upon this thread when I have some free time.

**Comment by vsivsi** [comment]
@kalmanh  Asked me to weigh-in here... file-collection's goal with regards to upload is to be flexible. It doesn't directly specify any browser/client mechanisms for implementing uploads (other than only currently supporting uploads via HTTP).

For convenience, it does wrap and provide server-side support for the resumable.js library (a completely separate project), but resumable.js itself is agnostic to how the user triggers an upload in the UI.

If you would just like to upload profile pictures, then resumable.js may be overkill. In that case, doing it "the old-fashioned way" via a form submission (via a single HTTP POST) is a fine approach. file-collection supports HTTP POST uploads directly if you specify a POST route when you set up the collection server-side. If you would like to include other data in the form (besides the uploaded file) then you will need to override the default HTTP POST handler.  See the documentation and source for more information:

https://github.com/vsivsi/meteor-file-collection#configuring-http-methods
https://github.com/vsivsi/meteor-file-collection/blob/master/src/http_access_server.coffee#L105-L129

As for advice on how to trigger/handle the file upload in your client UI, that is really up to you and the overall design and requirements of the application you are building. I'm personally partial to drag-and-drop interfaces over using a file-picker, but they each have their place.

Hope that helps.

**Comment by kalmanh** [comment]
@vsivsi - Thank you for weighing in on this...

I get the whole "agnostic" thing, but I am a big CoC (Convention over Configuration) guy. I understand that there are probably million ways to design this, but this problem has probably been solved gazillion times and there is no reason to reinvent the wheel again and again and again... :)

So... I just wanted to see if there was a standard way everyone is solving this problem IN METEOR.

**Comment by vsivsi** [comment]
When it comes to user facing design, I don't think there are many completely standard ways of doing anything. The CollectionFS client-side support is probably the closest thing for this in Meteor, it is very popular, but as near as I can tell the project is no longer maintained, largely (IMO) because it specified too much, and therefore became too complicated.

**Comment by brucejo75** [comment]
Looks like this got resolved for @kalmanh
